; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306


[env:native]
platform = native

test_build_src = yes

build_src_filter =
    +<StateOfChargeEstimator.cpp>